### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Yurii-Yenikeiev** [Yurii-Yenikeiev/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Dasan14** [comment]
Поєднання досвіду в медіа та юридичної освіти, вміння вільно розмовляти декількома мовами, участь у міжнародних проєктах дали мені можливість набути важливі м'які навички, особисті якості тайм-менеджера та вміння бути гнучкою у виборі сфери роботи, вміти швидко навчатися та продуктивно працювати.
