### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Yurii-Yenikeiev** [Yurii-Yenikeiev/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Dasan14** [comment]
Galina.bondarenko@sweetcv.com
+38(067)-111-11-11
Львів, Україна
