### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Yurii-Yenikeiev** [Yurii-Yenikeiev/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Dasan14** [comment]
Scalified LLC
Lead Backend EngineerSep, 2019-Present
Planned and implemented the migration of company products into a microservices architecture
Designed and implemented a high-performance Logstash and Elasticsearch monitoring system, which processed over 3000 metric events per second
Configured and maintained fully automated continuous delivery processes within the company
Established and managed a strong, motivated and result-focused backend team
EPAM Systems, Barclays Investment Bank
Senior Software Engineer Mar, 2017- Aug, 2019
Implemented various server-side banking applications, which involved the processing of over 1000 transactions per second
Effectively mentored and helped team members in the domain of distributed transactions, SAGA pattern, microservices orchestration approaches, etc.
Developed and enhanced monitoring, statistics collection and logging system
Luxoft
Software EngineerFeb, 2015 -June, 2019
Effectively used knowledge in the Big Data area to implement highly performant and reliable Social Media crawler system
Designed, implemented and delivered Facebook & Twitter API adapters into the existing system
Improved and optimized existing crawler modules that increased processing capacity to 1000+ posts per second

**Comment by Yurii-Yenikeiev** [comment]
Ок
